# Generated by Django 3.2.4 on 2022-05-09 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_2048', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game2048',
            name='game_state',
            field=models.JSONField(default=dict),
        ),
    ]
