# Generated by Django 3.2.4 on 2022-05-09 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_2048', '0002_alter_game2048_game_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game2048',
            name='game_state',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
